name: flutter_translate_annotations
description: Defines the annotations used by flutter_translate_gen to create statically-typed localization keys.
version: 2.1.0
homepage: https://bratan.me
repository: https://github.com/bratan/flutter_translate_annotations

environment:
  sdk: '>=2.12.0 <3.0.0'
